MasProjekt/Controllers/UmowasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasProjekt;

namespace MasProjekt.Controllers
{
    public class UmowasController : Controller
    {
        private MASEntities db = new MASEntities();

        private static int globalCount;

        public static int GlobalCount
        {
            get
            {
                return globalCount;
            }

            set
            {
                globalCount = value;
            }
        }

        // GET: Umowas
        public ActionResult Index()
        {
            return View(db.Umowas.ToList());
        }

        // GET: Umowas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Umowa umowa = db.Umowas.Find(id);
            umowa.Cena_calkowita = (umowa.Wesele.Szablon_uroczystości.Cena)*umowa.Wesele.Ilosc_gosci * (1+ ((decimal)umowa.Wesele.Konsultant.Prowizja / 100));
            db.SaveChanges();
            if (umowa == null)
            {
                return HttpNotFound();
            }
            return View(umowa);
        }

        // GET: Umowas/Create
        public ActionResult Create()
        {
            ViewBag.Status_Status_ID = new SelectList(db.Status, "Status_ID", "Nazwa");
            ViewBag.Wesele_Wesele_ID = new SelectList(db.Weseles, "Wesele_ID", "Nazwa");
            ViewBag.Klient_Osoba_Osoba_ID = new SelectList(db.Klients, "Osoba_ID", "Nazwisko");

            return View();
        }

        // POST: Umowas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Umowa_ID1,Data_podpisania,Cena_calkowita,Status_Status_ID,Wesele_Wesele_ID,Klient_Osoba_Osoba_ID")] Umowa umowa)
        {
            Random ran = new Random();
            umowa.Umowa_ID1 = ++globalCount + ran.Next(100, 500);

            if (ModelState.IsValid)
            {
                db.Umowas.Add(umowa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(umowa);
        }

        // GET: Umowas/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Status_Status_ID = new SelectList(db.Status, "Status_ID", "Nazwa");
            ViewBag.Wesele_Wesele_ID = new SelectList(db.Weseles, "Wesele_ID", "Nazwa");
            ViewBag.Klient_Osoba_Osoba_ID = new SelectList(db.Klients, "Osoba_ID", "Nazwisko");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Umowa umowa = db.Umowas.Find(id);
            if (umowa == null)
            {
                return HttpNotFound();
            }
            return View(umowa);
        }

        // POST: Umowas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Umowa_ID1,Data_podpisania,Cena_calkowita,Status_Status_ID,Wesele_Wesele_ID,Klient_Osoba_Osoba_ID")] Umowa umowa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(umowa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Status_Status_ID = new SelectList(db.Status, "Status_ID", "Nazwa");
            ViewBag.Wesele_Wesele_ID = new SelectList(db.Weseles, "Wesele_ID", "Nazwa");
            ViewBag.Klient_Osoba_Osoba_ID = new SelectList(db.Klients, "Osoba_ID", "Nazwisko");
            return View(umowa);
        }

        // GET: Umowas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Umowa umowa = db.Umowas.Find(id);
            if (umowa == null)
            {
                return HttpNotFound();
            }
            return View(umowa);
        }

        // POST: Umowas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Umowa umowa = db.Umowas.Find(id);
            db.Umowas.Remove(umowa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasProjekt/Controllers/WeselesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasProjekt;

namespace MasProjekt.Controllers
{
    public class WeselesController : Controller
    {
        private MASEntities db = new MASEntities();

        // GET: Weseles
        public ActionResult Index()
        {
            return View(db.Weseles.ToList());
        }

        // GET: Weseles/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // GET: Weseles/Create
        public ActionResult Create()
        {
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");

            return View();
        }

        // POST: Weseles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Wesele_ID,Nazwa,Ilosc_gosci,Data_wesela,Konsultant_Osoba_Osoba_ID,Szablon_uroczystości_Szablon_uroczystości_ID,Lokalizacja_Lokalizacja_ID")] Wesele wesele)
        {
            if (ModelState.IsValid)
            {
                db.Weseles.Add(wesele);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wesele);
        }

        // GET: Weseles/Edit/5
        public ActionResult Edit(decimal id)
        {
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // POST: Weseles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Wesele_ID,Nazwa,Ilosc_gosci,Data_wesela,Konsultant_Osoba_Osoba_ID,Szablon_uroczystości_Szablon_uroczystości_ID,Lokalizacja_Lokalizacja_ID")] Wesele wesele)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wesele).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");
            return View(wesele);
        }

        // GET: Weseles/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // POST: Weseles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Wesele wesele = db.Weseles.Find(id);
            db.Weseles.Remove(wesele);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasProjekt/Views/Weseles/Create.cshtml
@model MasProjekt.Wesele

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj nowe wesele</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Wesele</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ilosc_gosci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ilosc_gosci, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ilosc_gosci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_wesela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_wesela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data_wesela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Konsultant_Osoba_Osoba_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Konsultant_Osoba_Osoba_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Konsultant_Osoba_Osoba_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Szablon_uroczystości_Szablon_uroczystości_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lokalizacja_Lokalizacja_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Lokalizacja_Lokalizacja_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Lokalizacja_Lokalizacja_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
                <button class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Weseles")';return false;">Anuluj</button>
            </div>
        </div>
    </div>
}


@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

<script type="text/javascript">

     $(document).ready(function () {
         $('input[type=datetime]').datepicker({
             dateFormat: "yy-mm-dd",
             changeMonth: true,
             changeYear: true,
             yearRange: "-60:+0"
         });

     });
</script> 
}

 

MasProjekt/Views/Weseles/Delete.cshtml
@model MasProjekt.Wesele

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy napewno chcesz usunąć to wesele?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ilosc_gosci)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ilosc_gosci)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_wesela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_wesela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konsultant_Osoba_Osoba_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konsultant.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Szablon_uroczystości.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lokalizacja_Lokalizacja_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokalizacja.Nazwa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

MasProjekt/Views/Weseles/Details.cshtml
@model MasProjekt.Wesele

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ilosc_gosci)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ilosc_gosci)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_wesela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_wesela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konsultant_Osoba_Osoba_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konsultant.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Szablon_uroczystości.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lokalizacja_Lokalizacja_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokalizacja.Nazwa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Wesele_ID }) |
    @Html.ActionLink("Wróć do listy", "Index")
</p>

MasProjekt/Views/Weseles/Edit.cshtml
@model MasProjekt.Wesele

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Wesele</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Wesele_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ilosc_gosci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ilosc_gosci, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ilosc_gosci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data_wesela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_wesela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data_wesela, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Konsultant_Osoba_Osoba_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Konsultant_Osoba_Osoba_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Konsultant_Osoba_Osoba_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lokalizacja_Lokalizacja_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lokalizacja_Lokalizacja_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lokalizacja_Lokalizacja_ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Konsultant_Osoba_Osoba_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Konsultant_Osoba_Osoba_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Konsultant_Osoba_Osoba_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Szablon_uroczystości_Szablon_uroczystości_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lokalizacja_Lokalizacja_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Lokalizacja_Lokalizacja_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Lokalizacja_Lokalizacja_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

     $(document).ready(function () {
         $('input[type=datetime]').datepicker({
             dateFormat: "yy-mm-dd",
             changeMonth: true,
             changeYear: true,
             yearRange: "-60:+0"
         });

     });
    </script>
}

MasProjekt/Views/Weseles/Index.cshtml
@model IEnumerable<MasProjekt.Wesele>

@{
    ViewBag.Title = "Index";
}

<h2>Wesela</h2>

<p>
    @Html.ActionLink("Dodaj nowe wesele", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ilosc_gosci)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_wesela)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Konsultant_Osoba_Osoba_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Szablon_uroczystości_Szablon_uroczystości_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lokalizacja_Lokalizacja_ID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ilosc_gosci)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_wesela)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Konsultant.Nazwisko)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Szablon_uroczystości.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lokalizacja.Nazwa)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Wesele_ID }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.Wesele_ID }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.Wesele_ID })
        </td>
    </tr>
}

</table>

<center>
    <br />
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "Umowas")';return false;">Przejdź do podpisania umowy</button>
</center>