MasProjekt/Controllers/LokalizacjasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasProjekt;

namespace MasProjekt.Controllers
{
    public class LokalizacjasController : Controller
    {
        private MASEntities db = new MASEntities();

        // GET: Lokalizacjas
        public ActionResult Index()
        {
            return View(db.Lokalizacjas.ToList());
        }

        // GET: Lokalizacjas/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lokalizacja lokalizacja = db.Lokalizacjas.Find(id);
            if (lokalizacja == null)
            {
                return HttpNotFound();
            }
            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Lokalizacjas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nazwa,Adres,Powierzchnia,Lokalizacja_ID")] Lokalizacja lokalizacja)
        {
            if (ModelState.IsValid)
            {
                db.Lokalizacjas.Add(lokalizacja);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lokalizacja lokalizacja = db.Lokalizacjas.Find(id);
            if (lokalizacja == null)
            {
                return HttpNotFound();
            }
            return View(lokalizacja);
        }

        // POST: Lokalizacjas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nazwa,Adres,Powierzchnia,Lokalizacja_ID")] Lokalizacja lokalizacja)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lokalizacja).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lokalizacja);
        }

        // GET: Lokalizacjas/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lokalizacja lokalizacja = db.Lokalizacjas.Find(id);
            if (lokalizacja == null)
            {
                return HttpNotFound();
            }
            return View(lokalizacja);
        }

        // POST: Lokalizacjas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Lokalizacja lokalizacja = db.Lokalizacjas.Find(id);
            db.Lokalizacjas.Remove(lokalizacja);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasProjekt/Controllers/Szablon_uroczystościController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasProjekt;

namespace MasProjekt.Controllers
{
    public class Szablon_uroczystościController : Controller
    {
        private MASEntities db = new MASEntities();

        public decimal wyliczCene(Szablon_uroczystości szablon_uroczystości)
        {
            //Szablon_uroczystości szablon_uroczystości = new Szablon_uroczystości();
            szablon_uroczystości.Cena = szablon_uroczystości.Oferta_catering.Cena + szablon_uroczystości.Oferta_cukiernik.Cena + szablon_uroczystości.Oferta_kwiaciarnia.Cena;

            return szablon_uroczystości.Cena;
        }

        // GET: Szablon_uroczystości
        public ActionResult Index()
        {
            var szablon_uroczystości = db.Szablon_uroczystości.Include(s => s.Oferta_catering).Include(s => s.Oferta_cukiernik).Include(s => s.Oferta_kwiaciarnia);
            return View(szablon_uroczystości.ToList());
        }

        // GET: Szablon_uroczystości/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Szablon_uroczystości szablon_uroczystości = db.Szablon_uroczystości.Find(id);

            szablon_uroczystości.Cena = szablon_uroczystości.Oferta_catering.Cena + szablon_uroczystości.Oferta_cukiernik.Cena + szablon_uroczystości.Oferta_kwiaciarnia.Cena;
            db.SaveChanges();

            if (szablon_uroczystości == null)
            {
                return HttpNotFound();
            }
            return View(szablon_uroczystości);
        }

        // GET: Szablon_uroczystości/Create
        public ActionResult Create()
        {
            ViewBag.Oferta_catering_Oferta_catering_ID = new SelectList(db.Oferta_catering, "Oferta_catering_ID", "Nazwa");
            ViewBag.Oferta_cukiernik_Oferta_cukiernik_ID = new SelectList(db.Oferta_cukiernik, "Oferta_cukiernik_ID", "Nazwa");
            ViewBag.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID = new SelectList(db.Oferta_kwiaciarnia, "Oferta_kwiaciarnia_ID", "Nazwa");
            return View();
        }

        // POST: Szablon_uroczystości/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nazwa,Cena,Szablon_uroczystości_ID,Oferta_catering_Oferta_catering_ID,Oferta_cukiernik_Oferta_cukiernik_ID,Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID")] Szablon_uroczystości szablon_uroczystości)
        {
            

            if (ModelState.IsValid)
            {
                //szablon_uroczystości.Cena = szablon_uroczystości.Oferta_catering.Cena + szablon_uroczystości.Oferta_cukiernik.Cena + szablon_uroczystości.Oferta_kwiaciarnia.Cena;
                db.Szablon_uroczystości.Add(szablon_uroczystości);
                db.SaveChanges();
                //+ szablon_uroczystości.Oferta_cukiernik.Cena + szablon_uroczystości.Oferta_kwiaciarnia.Cena;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Oferta_catering_Oferta_catering_ID = new SelectList(db.Oferta_catering, "Oferta_catering_ID", "Nazwa", szablon_uroczystości.Oferta_catering_Oferta_catering_ID);
            ViewBag.Oferta_cukiernik_Oferta_cukiernik_ID = new SelectList(db.Oferta_cukiernik, "Oferta_cukiernik_ID", "Nazwa", szablon_uroczystości.Oferta_cukiernik_Oferta_cukiernik_ID);
            ViewBag.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID = new SelectList(db.Oferta_kwiaciarnia, "Oferta_kwiaciarnia_ID", "Nazwa", szablon_uroczystości.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID);
            
            return View(szablon_uroczystości);
        }

        // GET: Szablon_uroczystości/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Szablon_uroczystości szablon_uroczystości = db.Szablon_uroczystości.Find(id);

            if (szablon_uroczystości == null)
            {
                return HttpNotFound();
            }
            ViewBag.Oferta_catering_Oferta_catering_ID = new SelectList(db.Oferta_catering, "Oferta_catering_ID", "Nazwa", szablon_uroczystości.Oferta_catering_Oferta_catering_ID);
            ViewBag.Oferta_cukiernik_Oferta_cukiernik_ID = new SelectList(db.Oferta_cukiernik, "Oferta_cukiernik_ID", "Nazwa", szablon_uroczystości.Oferta_cukiernik_Oferta_cukiernik_ID);
            ViewBag.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID = new SelectList(db.Oferta_kwiaciarnia, "Oferta_kwiaciarnia_ID", "Nazwa", szablon_uroczystości.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID);
            return View(szablon_uroczystości);
        }

        // POST: Szablon_uroczystości/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nazwa,Cena,Szablon_uroczystości_ID,Oferta_catering_Oferta_catering_ID,Oferta_cukiernik_Oferta_cukiernik_ID,Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID")] Szablon_uroczystości szablon_uroczystości)
        {
            if (ModelState.IsValid)
            {
                db.Entry(szablon_uroczystości).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Oferta_catering_Oferta_catering_ID = new SelectList(db.Oferta_catering, "Oferta_catering_ID", "Nazwa", szablon_uroczystości.Oferta_catering_Oferta_catering_ID);
            ViewBag.Oferta_cukiernik_Oferta_cukiernik_ID = new SelectList(db.Oferta_cukiernik, "Oferta_cukiernik_ID", "Nazwa", szablon_uroczystości.Oferta_cukiernik_Oferta_cukiernik_ID);
            ViewBag.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID = new SelectList(db.Oferta_kwiaciarnia, "Oferta_kwiaciarnia_ID", "Nazwa", szablon_uroczystości.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID);
            return View(szablon_uroczystości);
        }

        // GET: Szablon_uroczystości/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Szablon_uroczystości szablon_uroczystości = db.Szablon_uroczystości.Find(id);
            if (szablon_uroczystości == null)
            {
                return HttpNotFound();
            }
            return View(szablon_uroczystości);
        }

        // POST: Szablon_uroczystości/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Szablon_uroczystości szablon_uroczystości = db.Szablon_uroczystości.Find(id);
            db.Szablon_uroczystości.Remove(szablon_uroczystości);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasProjekt/Controllers/WeselesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasProjekt;

namespace MasProjekt.Controllers
{
    public class WeselesController : Controller
    {
        private MASEntities db = new MASEntities();

        // GET: Weseles
        public ActionResult Index()
        {
            return View(db.Weseles.ToList());
        }

        // GET: Weseles/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // GET: Weseles/Create
        public ActionResult Create()
        {
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");

            return View();
        }

        // POST: Weseles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Wesele_ID,Nazwa,Ilosc_gosci,Data_wesela,Konsultant_Osoba_Osoba_ID,Szablon_uroczystości_Szablon_uroczystości_ID,Lokalizacja_Lokalizacja_ID")] Wesele wesele)
        {
            if (ModelState.IsValid)
            {
                db.Weseles.Add(wesele);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wesele);
        }

        // GET: Weseles/Edit/5
        public ActionResult Edit(decimal id)
        {
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // POST: Weseles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Wesele_ID,Nazwa,Ilosc_gosci,Data_wesela,Konsultant_Osoba_Osoba_ID,Szablon_uroczystości_Szablon_uroczystości_ID,Lokalizacja_Lokalizacja_ID")] Wesele wesele)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wesele).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Lokalizacja_Lokalizacja_ID = new SelectList(db.Lokalizacjas, "Lokalizacja_ID", "Nazwa");
            ViewBag.Konsultant_Osoba_Osoba_ID = new SelectList(db.Konsultants, "Osoba_ID", "Nazwisko");
            ViewBag.Szablon_uroczystości_Szablon_uroczystości_ID = new SelectList(db.Szablon_uroczystości, "Szablon_uroczystości_ID", "Nazwa");
            return View(wesele);
        }

        // GET: Weseles/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wesele wesele = db.Weseles.Find(id);
            if (wesele == null)
            {
                return HttpNotFound();
            }
            return View(wesele);
        }

        // POST: Weseles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Wesele wesele = db.Weseles.Find(id);
            db.Weseles.Remove(wesele);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasProjekt/Views/Szablon_uroczystości/Create.cshtml
@model MasProjekt.Szablon_uroczystości

@{
    ViewBag.Title = "Create";
}

<h2>Stwórz własny</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_catering_Oferta_catering_ID, "Oferta_catering_Oferta_catering_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_catering_Oferta_catering_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_catering_Oferta_catering_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_cukiernik_Oferta_cukiernik_ID, "Oferta_cukiernik_Oferta_cukiernik_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_cukiernik_Oferta_cukiernik_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_cukiernik_Oferta_cukiernik_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID, "Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
                <button class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Szablon_uroczystości")';return false;">Anuluj</button>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasProjekt/Views/Szablon_uroczystości/Delete.cshtml
@model MasProjekt.Szablon_uroczystości

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy napewno chcesz usunąć ten szablon?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_catering.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_catering.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_cukiernik.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_cukiernik.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_kwiaciarnia.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_kwiaciarnia.Nazwa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

MasProjekt/Views/Szablon_uroczystości/Details.cshtml
@model MasProjekt.Szablon_uroczystości

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_catering.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_catering.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_cukiernik.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_cukiernik.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oferta_kwiaciarnia.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oferta_kwiaciarnia.Nazwa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Szablon_uroczystości_ID }) |
    @Html.ActionLink("Wróć do listy", "Index")
</p>

MasProjekt/Views/Szablon_uroczystości/Edit.cshtml
@model MasProjekt.Szablon_uroczystości

@{
    ViewBag.Title = "Edit";
}

<h2>Edytuj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Szablon_uroczystości_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_catering_Oferta_catering_ID, "Oferta_catering_Oferta_catering_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_catering_Oferta_catering_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_catering_Oferta_catering_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_cukiernik_Oferta_cukiernik_ID, "Oferta_cukiernik_Oferta_cukiernik_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_cukiernik_Oferta_cukiernik_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_cukiernik_Oferta_cukiernik_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID, "Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasProjekt/Views/Szablon_uroczystości/Index.cshtml
@model IEnumerable<MasProjekt.Szablon_uroczystości>

@{
    ViewBag.Title = "Index";
}

<h2>Szablony uroczystości</h2>

<p>
    @Html.ActionLink("Stwórz własny", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Oferta_catering_Oferta_catering_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Oferta_cukiernik.Oferta_cukiernik_Oferta_cukiernik_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Oferta_kwiaciarnia_Oferta_kwiaciarnia_ID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Oferta_catering.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Oferta_cukiernik.Nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Oferta_kwiaciarnia.Nazwa)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.Szablon_uroczystości_ID }) |
            @Html.ActionLink("Wylicz cenę", "Details", new { id=item.Szablon_uroczystości_ID }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.Szablon_uroczystości_ID })
        </td>
    </tr>
}

</table>

<center>
    <br />
    <button class="btn btn-success" onclick="location.href='@Url.Action("Index", "Lokalizacjas")';return false;">Przeglądaj lokalizacje</button>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create", "Weseles")';return false;">Utwórz wesele!</button>
</center>